# Configuración para PostgreSQL
spring.datasource.url=jdbc:postgresql://<HOST_QUE_COPIASTE>:<PUERTO>/<NOMBRE_BD>
spring.datasource.username=<TU_USUARIO>
spring.datasource.password=<TU_PASSWORD>

# Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update