# Driver para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# URL de conexión (Render te dará estos valores cuando crees la BD)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update